steps:

- name: 'gcr.io/cloud-builders/docker'
  id: latest
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest',
    '.'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.7
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.7',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.7',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.8',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8-alpine
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.8',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.9',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9-alpine
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.9',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.10',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10-alpine
  args: [
    'build',
    '--build-arg',
    'PYTHON_VERSION=3.10',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

images:
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.7'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10-alpine'

timeout: 7200s
