steps:

- name: 'gcr.io/cloud-builders/docker'
  id: latest
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest',
    '.'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.7
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.7',
    'python3.7/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8',
    'python3.8/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8-alpine
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8-alpine',
    'python3.8-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9',
    'python3.9/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9-alpine
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9-alpine',
    'python3.9-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10',
    'python3.10/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10-alpine
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10-alpine',
    'python3.10-alpine/'
  ]
  waitFor: ['-']

images:
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.7'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.8-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.9-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-bash-pipeline:latest-python3.10-alpine'

timeout: 7200s
